#!/bin/bash
#
#  By: i3-Arch
#	Ice i hope this helps with if else statements    :3
################
red=$(tput setaf 1)
white=$(tput setaf 7)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
clear
	echo
	echo ${white}
	echo " What is your favorite LINUX distro "		## first comment right here :)
read DISTRO								## read waits for user input
		echo ${yellow}
		echo " So you like $DISTRO huh? "
		echo
if [ $DISTRO == archlinux ]
then
	echo
	echo " DAT MASTER RACE BROSEF ! "
			elif [ $DISTRO == arch ] 
				then
					echo
					echo " DAT MASTER RACE BROSEF ! "
					echo
		elif [ $DISTRO == ubuntu ]
			then
				echo
				echo -e You should commit suicide `xdg-open http://meatspin.com > /dev/null 2>&1`    ## This will open a browser huehuehue
				echo
	elif [ $DISTRO == mint ]					## Multiple elif statements can be used :)
		then
			echo
			echo -e You are such a fggt... `xdg-open http://meatspin.com > /dev/null 2>&1`
else 				### This is what will happen if your if and elif statements are false... its called an else statement
	echo 
	echo " Seems un-exciting... Archlinux is master-race bro"
	echo
fi		### This closes the if statement we opened earlier
		echo ${white}
		echo " How old are you ? " 
		echo ${yellow} 
read AGE				
			echo ${red}
			echo " So you are $AGE ? "  
			echo
	if [ $AGE -lt 18 ]
		then
			echo
			echo " Your age is scary...  "
			echo
				elif [ $AGE -gt 28 ]            ## showing diff ways to do things   ....  -gt is greater than     -lt   is less than   and -eq is equal
					then
			       		echo
       			   		echo -e ${yellow} you old ass ho i aint drunk
				   		echo
			elif [ $AGE -eq 18 ] 
				then 
					echo 
					echo " Daaaaaamn  let me tap that ... if you look good ofc "
					echo
		else
			echo -e ehh... the age seems ok  ... sup ... maybe we should get outta here yo
	fi
			if [ $AGE == 22 ]      		
			then
				echo
				echo -e ${yellow} Cool im 22 also !
				echo
	else					
		echo
		echo -e ${white}  anywayz 
		echo
			fi							
				echo ${white}
				echo -e So do you understand how to create a bash script yet? ${yellow}   ##  ( LOWERCASE ) Acceptable answers here are    yes  and  no
				echo
read ANSWER
if [ $ANSWER == yes ]
then
		echo ${green}
		echo " Prove it then fggt? "
		echo " Write me one..... "
		echo
	elif [ $ANSWER == no ]
		then
			echo
			echo " You should start practicing then fggt"
			echo
		elif [ $ANSWER == YES ]
			then 
				echo
				echo " Huehuehue... write me one then"
				echo
	else
		echo
		echo -e ${yellow} To bad... we couldve had somethin... 
fi
				echo
				echo -e ${white} So whats your name? ${yellow} 
read NAME
			echo
			echo -e ${white}  Well this is the end of this script $NAME ....
if [ $NAME == ice ]			## Here we actually specify what to do if the user enters ' ice ' as the name
	then
		echo
		echo -e ${green} bye $NAME you fggt
		echo
	elif [ $NAME == iceland ]
		then
			echo
			echo -e ${yellow} u can fap to me later $NAME .... 
else
	echo 
	echo -e ${red} Fggt
fi
