#!/bin/bash
#
# 	BY: THE GREATEST PERSON IN THE WORLD!!!!
#
###################
clear
	echo
	echo -e " \n \n $(date) " 
	
	echo
	echo
	read -n1 -t1 any_key
	
	echo " Initiating contact sequence... "
	read -n1 -t5 any_key 
	echo " Contact sequence initiated... "
	read -n1 -t2 any_key  ## I added this so it would recognize any key because I know you are an impatient faggot who will be leik "hurr durr ice ur skript no work. it frozen.. hahahaha FAIL" -_- inb4 "shift and ctrl don't work, so u still fail" 
	echo
	echo
	
	echo -e " Hello $USER. Only continue if you think you are worthy and have the time. You should not continue this quest unless you think you are worthy. "
	echo
	
	echo Press any key to start, if you think you are worthy
	read -n1 -t10 any_key
	echo " Start!!!!! "
	read -n1 -t2 any_key

	echo						
	echo -e " What is your favorite operating system $USER "
	echo
read SYSTEM
if [ $SYSTEM == archlinux -o $SYSTEM == arch ]
then
		echo
		echo " $SYSTEM really?  "
		echo
				echo
				echo " $USER you can't be serious. You are an elitist faggot and need to go fuck yourself with a cactus and then lower your blood pressure by slitting your wrists. "
				echo
	elif [ $SYSTEM == linux -o $SYSTEM == cent -o $SYSTEM == mint ]
			then
				echo
				echo " $SYSTEM is an okay choice "
				echo
				echo
				echo " I guess I can be your friend. Consider yourself lucky and act accordingly. "
	else	
			echo
			echo " huehue im ice durr hurr"
fi
