#!/bin/bash
## BY : i3-Arch
################
HUE=$(uname -r)
ipaddress=$(curl wtfismyip.com/text > ~/.IP.txt 2> ~/.hue.txt)
homoo=$(cat ~/.IP.txt)
removeTXT=$(rm ~/.IP.txt && rm ~/.hue.txt)

yournamebro () {
		clear
		printf " \n So whats your first name ? \n "
		read YourName
		printf " \n So your name is $YourName ? \n "
		if [ "$YourName" == Jeremy -o "$YourName" == JEREMY -o "$YourName" == jeremy ]
			then 
				printf " \n Are you my creator ? Because his name is Jeremy ? \n "
			else
				printf " \n And you are who again ? \n "
				printf " \n Nevermind... \n "
				printf " \n I dont care to know \n"
		fi
sleep 3
}

showkernelbro () {
		printf " \n \n You're running $HUE kernel \n "  
}

agethangbro () {
	printf " \n What is your age? \n "
	read AGE
	print " \n \n So wait.... you're $AGE ? \n "
	if [ "$AGE" == 21 ]
		then
			printf " \n Lets go to the bar bro \n \n "
		elif [ "$AGE" -lt 21 ]
			then 
				printf " \n To young to live that bar life bro... be older \n "
		elif [ "$AGE" -gt 30 ]
			then
				printf " \n Yeah im gunna pass on going to the bar with you... you're kinda old \n"
		else
			printf " \n Seems legit... Lets go to the bar.. since you're over 21 \n "
	fi
}

genderthangbro () {
	printf " \n What Gender are You ?   (M)ale (F)emale (O)ther \n \n "
	read GENDER
	if [ "$GENDER" == M -o "$GENDER" == m -o "$GENDER" == o -o "$GENDER" == O ]
		then  
			printf " \n I am disapoint \n "
		elif [ "$GENDER" == F -o "$GENDER" == f -a "$AGE" -gt 18 -a "$AGE" -lt 30 ]
				then
					printf " \n Sex noa $YourName \n "
		else
		   		printf " \n Im not interested.. You're a ' $GENDER ' thats $AGE \n "
		if [ "$AGE" -lt 18 ] 
			then 
				printf " \n FAIL..YOU'RE less than 18 \n "
		fi
	fi
	if [ "$GENDER" == o -o "$GENDER" == O ]
		then 
			printf " \n You must be a kangaroo \n "
			printf " \n Also $ipaddress \n "
			printf " \n Your ip is $homoo ... Now time to H4x0r my first kangaroo \n "
			printf "$removeTXT"
		else 
			printf " \n Everything is as it should be .....  \n "
		if [ "$GENDER" == m -o "$GENDER" == M -o "$GENDER" == f -o "$GENDER" == F ]  
			then
				printf "$ipaddress"
				printf " \n Your ip is $homoo  ... Now time to H4x0r You ! \n "
				printf "$removeTXT"
			else
				printf " \n Something went wrong \n "
		fi
	fi
}

ENSURE_CLEAN () {
	rm ~/.hue.txt
	rm ~/.IP.txt	
}

MAIN () {
	yournamebro
	showkernelbro
	agethangbro
	genderthangbro
	ENSURE_CLEAN
}
MAIN
